use serde::Serialize;

#[derive(Debug, Clone, Copy, Serialize)]
pub struct EndpointSpec {
    pub path: &'static str,
    pub access: &'static str,
    pub source: &'static str,
    pub handler: &'static str,
}

pub static ENDPOINTS: &[EndpointSpec] = &[
    EndpointSpec { path: "/", access: "public", source: "main.go:114", handler: "func(w http.ResponseWriter, r *http.Request; h; http.HandlerFunc(func(w http.ResponseWriter, r *http.Request; mrouter(fs" },
    EndpointSpec { path: "/AOB/", access: "public", source: "system.go:41", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/AOB/SystemAOB/functions/info/version.inf", access: "public", source: "system.go:44", handler: "systemIdServeVersonNumber" },
    EndpointSpec { path: "/AOB/SystemAOB/functions/system_statistic/getDriveStat.php", access: "public", source: "system.go:45", handler: "systemIdGetDriveStates" },
    EndpointSpec { path: "/AOB/hb.php", access: "public", source: "system.go:40", handler: "systemIdResponseBetaScan" },
    EndpointSpec { path: "/alpnas/auth/admin", access: "public", source: "auth.go:81", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/api/ajgi/addExt", access: "authenticated", source: "agi.go:88", handler: "gw.AddExternalEndPoint" },
    EndpointSpec { path: "/api/ajgi/exec", access: "public", source: "agi.go:76", handler: "gw.HandleAgiExecutionRequestWithToken" },
    EndpointSpec { path: "/api/ajgi/interface", access: "public", source: "agi.go:47", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/api/ajgi/listExt", access: "authenticated", source: "agi.go:87", handler: "gw.ListExternalEndpoint" },
    EndpointSpec { path: "/api/ajgi/rmExt", access: "authenticated", source: "agi.go:89", handler: "gw.RemoveExternalEndPoint" },
    EndpointSpec { path: "/api/auth/login", access: "public-or-token", source: "auth.go:62", handler: "authAgent.HandleAutologinTokenLogin" },
    EndpointSpec { path: "/ldapLogin.html", access: "public-or-token", source: "ldap.go:47", handler: "ldapHandler.HandleLoginPage" },
    EndpointSpec { path: "/media/", access: "public-or-token", source: "mediaServer.go:40", handler: "mediaServer.ServerMedia" },
    EndpointSpec { path: "/media/download/", access: "public-or-token", source: "mediaServer.go:41", handler: "mediaServer.ServerMedia" },
    EndpointSpec { path: "/media/getMime/", access: "public-or-token", source: "mediaServer.go:42", handler: "mediaServer.ServeMediaMime" },
    EndpointSpec { path: "/media/transcode/", access: "public-or-token", source: "mediaServer.go:48", handler: "func(w http.ResponseWriter, r *http.Request; mediaServer.ServeVideoWithTranscode" },
    EndpointSpec { path: "/public/register/checkPublicRegister", access: "public", source: "register.go:42", handler: "registerHandler.HandleRegisterCheck" },
    EndpointSpec { path: "/public/register/handleRegister.html", access: "public", source: "register.go:41", handler: "registerHandler.HandleRegisterRequest" },
    EndpointSpec { path: "/public/register/register.html", access: "public", source: "register.go:40", handler: "registerHandler.HandleRegisterInterface" },
    EndpointSpec { path: "/reset.system", access: "public", source: "system.resetpw.go:27", handler: "system_resetpw_alpnasResetSystem" },
    EndpointSpec { path: "/share", access: "public-or-token", source: "file_system.go:210", handler: "shareManager.HandleShareAccess" },
    EndpointSpec { path: "/ssdp.xml", access: "public", source: "mod/network/ssdp/ssdp.go:75", handler: "a.handleSSDP" },
    EndpointSpec { path: "/system/ajgi/interface", access: "public", source: "agi.go:37", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/apt/list", access: "authenticated", source: "apt.go:28", handler: "apt.HandlePackageListRequest" },
    EndpointSpec { path: "/system/arsm/aecron/add", access: "authenticated", source: "scheduler.go:91", handler: "systemScheduler.HandleAddJob" },
    EndpointSpec { path: "/system/arsm/aecron/list", access: "public", source: "scheduler.go:82", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/arsm/aecron/listlog", access: "authenticated", source: "scheduler.go:93", handler: "systemScheduler.HandleShowLog" },
    EndpointSpec { path: "/system/arsm/aecron/remove", access: "authenticated", source: "scheduler.go:92", handler: "systemScheduler.HandleJobRemoval" },
    EndpointSpec { path: "/system/auth/blacklist/ban", access: "admin", source: "auth.go:131", handler: "authAgent.BlacklistManager.HandleAddBannedIP" },
    EndpointSpec { path: "/system/auth/blacklist/enable", access: "admin", source: "auth.go:129", handler: "authAgent.BlacklistManager.HandleSetBlacklistEnable" },
    EndpointSpec { path: "/system/auth/blacklist/list", access: "admin", source: "auth.go:130", handler: "authAgent.BlacklistManager.HandleListBannedIPs" },
    EndpointSpec { path: "/system/auth/blacklist/unban", access: "admin", source: "auth.go:132", handler: "authAgent.BlacklistManager.HandleRemoveBannedIP" },
    EndpointSpec { path: "/system/auth/checkLogin", access: "public", source: "auth.go:61", handler: "authAgent.CheckLogin" },
    EndpointSpec { path: "/system/auth/csvimport", access: "admin", source: "auth.go:96", handler: "authAgent.HandleCreateUserAccountsFromCSV" },
    EndpointSpec { path: "/system/auth/groupdel", access: "admin", source: "auth.go:97", handler: "authAgent.HandleUserDeleteByGroup" },
    EndpointSpec { path: "/system/auth/ldap/checkldap", access: "public", source: "ldap.go:48", handler: "ldapHandler.HandleCheckLDAP" },
    EndpointSpec { path: "/system/auth/ldap/config/read", access: "admin", source: "ldap.go:38", handler: "ldapHandler.ReadConfig" },
    EndpointSpec { path: "/system/auth/ldap/config/syncorizeUser", access: "admin", source: "ldap.go:41", handler: "ldapHandler.SynchronizeUser" },
    EndpointSpec { path: "/system/auth/ldap/config/testConnection", access: "admin", source: "ldap.go:40", handler: "ldapHandler.TestConnection" },
    EndpointSpec { path: "/system/auth/ldap/config/write", access: "admin", source: "ldap.go:39", handler: "ldapHandler.WriteConfig" },
    EndpointSpec { path: "/system/auth/ldap/login", access: "public", source: "ldap.go:44", handler: "ldapHandler.HandleLogin" },
    EndpointSpec { path: "/system/auth/ldap/newPassword", access: "public", source: "ldap.go:46", handler: "ldapHandler.HandleNewPasswordPage" },
    EndpointSpec { path: "/system/auth/ldap/setPassword", access: "public", source: "ldap.go:45", handler: "ldapHandler.HandleSetPassword" },
    EndpointSpec { path: "/system/auth/logger/index", access: "admin", source: "auth.go:109", handler: "authAgent.Logger.HandleIndexListing" },
    EndpointSpec { path: "/system/auth/logger/list", access: "admin", source: "auth.go:110", handler: "authAgent.Logger.HandleTableListing" },
    EndpointSpec { path: "/system/auth/login", access: "public-or-token", source: "auth.go:58", handler: "authAgent.HandleLogin" },
    EndpointSpec { path: "/system/auth/logout", access: "public", source: "auth.go:59", handler: "authAgent.HandleLogout" },
    EndpointSpec { path: "/system/auth/oauth/authorize", access: "public", source: "oauth.go:23", handler: "oAuthHandler.HandleAuthorize" },
    EndpointSpec { path: "/system/auth/oauth/checkoauth", access: "public", source: "oauth.go:24", handler: "oAuthHandler.CheckOAuth" },
    EndpointSpec { path: "/system/auth/oauth/config/read", access: "admin", source: "oauth.go:25", handler: "oAuthHandler.ReadConfig" },
    EndpointSpec { path: "/system/auth/oauth/config/write", access: "admin", source: "oauth.go:26", handler: "oAuthHandler.WriteConfig" },
    EndpointSpec { path: "/system/auth/oauth/login", access: "public", source: "oauth.go:22", handler: "oAuthHandler.HandleLogin" },
    EndpointSpec { path: "/system/auth/register", access: "public", source: "auth.go:60", handler: "authAgent.HandleRegister" },
    EndpointSpec { path: "/system/auth/u/list", access: "authenticated", source: "auth.go:153", handler: "authAgent.SwitchableAccountManager.HandleSwitchableAccountListing" },
    EndpointSpec { path: "/system/auth/u/logoutAll", access: "authenticated", source: "auth.go:155", handler: "authAgent.SwitchableAccountManager.HandleLogoutAllAccounts" },
    EndpointSpec { path: "/system/auth/u/p/list", access: "public", source: "auth.go:158", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/auth/u/switch", access: "authenticated", source: "auth.go:154", handler: "authAgent.SwitchableAccountManager.HandleAccountSwitch" },
    EndpointSpec { path: "/system/auth/unregister", access: "admin", source: "user.go:98", handler: "authAgent.HandleUnregister" },
    EndpointSpec { path: "/system/auth/whitelist/enable", access: "admin", source: "auth.go:123", handler: "authAgent.WhitelistManager.HandleSetWhitelistEnable" },
    EndpointSpec { path: "/system/auth/whitelist/list", access: "admin", source: "auth.go:124", handler: "authAgent.WhitelistManager.HandleListWhitelistedIPs" },
    EndpointSpec { path: "/system/auth/whitelist/set", access: "admin", source: "auth.go:125", handler: "authAgent.WhitelistManager.HandleAddWhitelistedIP" },
    EndpointSpec { path: "/system/auth/whitelist/unset", access: "admin", source: "auth.go:126", handler: "authAgent.WhitelistManager.HandleRemoveWhitelistedIP" },
    EndpointSpec { path: "/system/autologin/create", access: "admin", source: "setting.advance.go:49", handler: "autoLoginHandler.HandleUserTokenCreation" },
    EndpointSpec { path: "/system/autologin/delete", access: "admin", source: "setting.advance.go:50", handler: "autoLoginHandler.HandleUserTokenRemoval" },
    EndpointSpec { path: "/system/autologin/list", access: "admin", source: "setting.advance.go:48", handler: "autoLoginHandler.HandleUserTokensListing" },
    EndpointSpec { path: "/system/bootflags", access: "admin", source: "startup.flags.go:39", handler: "handleBootFlagsFunction" },
    EndpointSpec { path: "/system/cluster/record", access: "authenticated", source: "cluster.go:57", handler: "NeighbourDiscoverer.HandleScanRecord" },
    EndpointSpec { path: "/system/cluster/scan", access: "authenticated", source: "cluster.go:56", handler: "NeighbourDiscoverer.HandleScanningRequest" },
    EndpointSpec { path: "/system/cluster/wol", access: "authenticated", source: "cluster.go:58", handler: "NeighbourDiscoverer.HandleWakeOnLan" },
    EndpointSpec { path: "/system/csrf/new", access: "authenticated", source: "security.go:42", handler: "CSRFTokenManager.HandleNewToken" },
    EndpointSpec { path: "/system/desktop/createShortcut", access: "authenticated", source: "desktop.go:42", handler: "desktop_shortcutHandler" },
    EndpointSpec { path: "/system/desktop/files", access: "authenticated", source: "desktop.go:38", handler: "desktop_fileLocation_handler" },
    EndpointSpec { path: "/system/desktop/host", access: "authenticated", source: "desktop.go:39", handler: "desktop_hostdetailHandler" },
    EndpointSpec { path: "/system/desktop/listDesktop", access: "authenticated", source: "desktop.go:36", handler: "desktop_listFiles" },
    EndpointSpec { path: "/system/desktop/opr/renameShortcut", access: "authenticated", source: "desktop.go:45", handler: "desktop_handleShortcutRename" },
    EndpointSpec { path: "/system/desktop/preference", access: "authenticated", source: "desktop.go:41", handler: "desktop_preference_handler" },
    EndpointSpec { path: "/system/desktop/theme", access: "authenticated", source: "desktop.go:37", handler: "desktop_theme_handler" },
    EndpointSpec { path: "/system/desktop/user", access: "authenticated", source: "desktop.go:40", handler: "desktop_handleUserInfo" },
    EndpointSpec { path: "/system/disk/alpnas/list", access: "authenticated", source: "disk_alpnas.go:78", handler: "alpnasHandleDriveList" },
    EndpointSpec { path: "/system/disk/alpnas/mount", access: "authenticated", source: "disk_alpnas.go:80", handler: "alpnasHandleDriveMount" },
    EndpointSpec { path: "/system/disk/alpnas/rescan", access: "authenticated", source: "disk_alpnas.go:79", handler: "alpnasHandleDriveRescan" },
    EndpointSpec { path: "/system/disk/alpnas/unmount", access: "authenticated", source: "disk_alpnas.go:81", handler: "alpnasHandleDriveUnmount" },
    EndpointSpec { path: "/system/disk/devices/list", access: "admin", source: "disk.go:186", handler: "raidManager.HandleListUsableDevices" },
    EndpointSpec { path: "/system/disk/devices/model", access: "admin", source: "disk.go:187", handler: "raidManager.HandleResolveDiskModelLabel" },
    EndpointSpec { path: "/system/disk/diskmg/format", access: "admin", source: "disk.go:210", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/disk/diskmg/mount", access: "admin", source: "disk.go:205", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/disk/diskmg/mpt", access: "admin", source: "disk.go:229", handler: "diskmg.HandleListMountPoints" },
    EndpointSpec { path: "/system/disk/diskmg/platform", access: "admin", source: "disk.go:204", handler: "diskmg.HandlePlatform" },
    EndpointSpec { path: "/system/disk/diskmg/view", access: "authenticated", source: "disk.go:203", handler: "diskmg.HandleView" },
    EndpointSpec { path: "/system/disk/quota/quotaDist", access: "public", source: "quota.go:21", handler: "system_disk_quota_handleFileDistributionView" },
    EndpointSpec { path: "/system/disk/quota/quotaInfo", access: "public", source: "quota.go:20", handler: "system_disk_quota_handleQuotaInfo" },
    EndpointSpec { path: "/system/disk/quota/setQuota", access: "public", source: "quota.go:19", handler: "system_disk_quota_setQuota" },
    EndpointSpec { path: "/system/disk/raid/addMemeber", access: "admin", source: "disk.go:182", handler: "raidManager.HandleAddDiskToRAIDVol" },
    EndpointSpec { path: "/system/disk/raid/assemble", access: "admin", source: "disk.go:172", handler: "func(w http.ResponseWriter, r *http.Request; raidManager.HandleRaidDevicesAssemble" },
    EndpointSpec { path: "/system/disk/raid/detail", access: "admin", source: "disk.go:180", handler: "raidManager.HandleLoadArrayDetail" },
    EndpointSpec { path: "/system/disk/raid/devinfo", access: "admin", source: "disk.go:181", handler: "raidManager.HandlListChildrenDeviceInfo" },
    EndpointSpec { path: "/system/disk/raid/format", access: "admin", source: "disk.go:179", handler: "raidManager.HandleFormatRaidDevice" },
    EndpointSpec { path: "/system/disk/raid/grow", access: "admin", source: "disk.go:178", handler: "raidManager.HandleGrowRAIDArray" },
    EndpointSpec { path: "/system/disk/raid/list", access: "admin", source: "disk.go:164", handler: "raidManager.HandleListRaidDevices" },
    EndpointSpec { path: "/system/disk/raid/new", access: "admin", source: "disk.go:165", handler: "raidManager.HandleCreateRAIDDevice" },
    EndpointSpec { path: "/system/disk/raid/overview", access: "admin", source: "disk.go:163", handler: "raidManager.HandleRenderOverview" },
    EndpointSpec { path: "/system/disk/raid/reload", access: "admin", source: "disk.go:191", handler: "raidManager.HandleMdadmFlushReload" },
    EndpointSpec { path: "/system/disk/raid/remove", access: "admin", source: "disk.go:166", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/disk/raid/removeMemeber", access: "admin", source: "disk.go:183", handler: "raidManager.HandleRemoveDiskFromRAIDVol" },
    EndpointSpec { path: "/system/disk/smart/getSMART", access: "authenticated", source: "disk.go:145", handler: "smartListener.GetSMART" },
    EndpointSpec { path: "/system/disk/space/largeFiles", access: "authenticated", source: "disk.go:87", handler: "lfs.HandleLargeFileList" },
    EndpointSpec { path: "/system/disk/space/list", access: "authenticated", source: "disk.go:78", handler: "diskspace.HandleDiskSpaceList" },
    EndpointSpec { path: "/system/disk/space/resolve", access: "authenticated", source: "disk.go:82", handler: "dc.HandleCapacityResolving" },
    EndpointSpec { path: "/system/disk/space/tmp", access: "authenticated", source: "disk.go:83", handler: "dc.HandleTmpCapacityResolving" },
    EndpointSpec { path: "/system/file_system/clearTrash", access: "authenticated", source: "file_system.go:101", handler: "system_fs_clearTrashBin" },
    EndpointSpec { path: "/system/file_system/fileOpr", access: "authenticated", source: "file_system.go:91", handler: "system_fs_handleOpr" },
    EndpointSpec { path: "/system/file_system/getProperties", access: "authenticated", source: "file_system.go:104", handler: "system_fs_getFileProperties" },
    EndpointSpec { path: "/system/file_system/handleCacheRender", access: "authenticated", source: "file_system.go:112", handler: "system_fs_handleCacheRender" },
    EndpointSpec { path: "/system/file_system/handleFilePermission", access: "authenticated", source: "file_system.go:107", handler: "system_fs_handleFilePermission" },
    EndpointSpec { path: "/system/file_system/handleFolderCache", access: "authenticated", source: "file_system.go:111", handler: "system_fs_handleFolderCache" },
    EndpointSpec { path: "/system/file_system/listDir", access: "authenticated", source: "file_system.go:93", handler: "system_fs_handleList" },
    EndpointSpec { path: "/system/file_system/listDirHash", access: "authenticated", source: "file_system.go:94", handler: "system_fs_handleDirHash" },
    EndpointSpec { path: "/system/file_system/listDrives", access: "authenticated", source: "file_system.go:96", handler: "system_fs_listDrives" },
    EndpointSpec { path: "/system/file_system/listRoots", access: "authenticated", source: "file_system.go:95", handler: "system_fs_listRoot" },
    EndpointSpec { path: "/system/file_system/listTrash", access: "authenticated", source: "file_system.go:99", handler: "system_fs_scanTrashBin" },
    EndpointSpec { path: "/system/file_system/loadThumbnail", access: "authenticated", source: "file_system.go:113", handler: "system_fs_handleThumbnailLoad" },
    EndpointSpec { path: "/system/file_system/lowmemUpload", access: "authenticated", source: "file_system.go:87", handler: "system_fs_handleLowMemoryUpload" },
    EndpointSpec { path: "/system/file_system/newItem", access: "authenticated", source: "file_system.go:97", handler: "system_fs_handleNewObjects" },
    EndpointSpec { path: "/system/file_system/ongoing", access: "authenticated", source: "file_system.go:217", handler: "system_fs_HandleOnGoingTasks" },
    EndpointSpec { path: "/system/file_system/preference", access: "authenticated", source: "file_system.go:98", handler: "system_fs_handleUserPreference" },
    EndpointSpec { path: "/system/file_system/restoreTrash", access: "authenticated", source: "file_system.go:102", handler: "system_fs_restoreFile" },
    EndpointSpec { path: "/system/file_system/search", access: "authenticated", source: "file_system.go:108", handler: "system_fs_handleFileSearch" },
    EndpointSpec { path: "/system/file_system/share/checkShared", access: "authenticated", source: "file_system.go:205", handler: "shareManager.HandleShareCheck" },
    EndpointSpec { path: "/system/file_system/share/delete", access: "authenticated", source: "file_system.go:203", handler: "shareManager.HandleDeleteShare" },
    EndpointSpec { path: "/system/file_system/share/edit", access: "authenticated", source: "file_system.go:204", handler: "shareManager.HandleEditShare" },
    EndpointSpec { path: "/system/file_system/share/list", access: "authenticated", source: "file_system.go:206", handler: "shareManager.HandleListAllShares" },
    EndpointSpec { path: "/system/file_system/share/new", access: "authenticated", source: "file_system.go:202", handler: "shareManager.HandleCreateNewShare" },
    EndpointSpec { path: "/system/file_system/sortMode", access: "authenticated", source: "file_system.go:116", handler: "system_fs_handleFolderSortModePreference" },
    EndpointSpec { path: "/system/file_system/upload", access: "authenticated", source: "file_system.go:86", handler: "system_fs_handleUpload" },
    EndpointSpec { path: "/system/file_system/validateFileOpr", access: "authenticated", source: "file_system.go:90", handler: "system_fs_validateFileOpr" },
    EndpointSpec { path: "/system/file_system/versionHistory", access: "authenticated", source: "file_system.go:105", handler: "system_fs_FileVersionHistory" },
    EndpointSpec { path: "/system/file_system/ws/fileOpr", access: "authenticated", source: "file_system.go:92", handler: "system_fs_handleWebSocketOpr" },
    EndpointSpec { path: "/system/file_system/ws/listTrash", access: "authenticated", source: "file_system.go:100", handler: "system_fs_WebSocketScanTrashBin" },
    EndpointSpec { path: "/system/file_system/zipHandler", access: "authenticated", source: "file_system.go:103", handler: "system_fs_zipHandler" },
    EndpointSpec { path: "/system/id/ping", access: "public", source: "system.go:79", handler: "systemIdHandlePing" },
    EndpointSpec { path: "/system/id/requestInfo", access: "public", source: "system.go:36", handler: "systemIdHandleRequest" },
    EndpointSpec { path: "/system/info/getArOZInfo", access: "public", source: "system.info.go:132", handler: "infoServer.GetArOZInfo" },
    EndpointSpec { path: "/system/info/getCPUinfo", access: "authenticated", source: "system.info.go:82", handler: "info.GetCPUInfo" },
    EndpointSpec { path: "/system/info/getDriveStat", access: "authenticated", source: "system.info.go:84", handler: "info.GetDriveStat" },
    EndpointSpec { path: "/system/info/getRAMinfo", access: "authenticated", source: "system.info.go:88", handler: "info.GetRamInfo" },
    EndpointSpec { path: "/system/info/getRuntimeInfo", access: "authenticated", source: "system.info.go:129", handler: "InfoHandleGetRuntimeInfo" },
    EndpointSpec { path: "/system/info/getUsageInfo", access: "authenticated", source: "system.info.go:112", handler: "InfoHandleTaskInfo" },
    EndpointSpec { path: "/system/info/ifconfig", access: "authenticated", source: "system.info.go:83", handler: "info.Ifconfig" },
    EndpointSpec { path: "/system/info/license", access: "public", source: "system.go:76", handler: "systemHandleListLicense" },
    EndpointSpec { path: "/system/info/usbPorts", access: "authenticated", source: "system.info.go:85", handler: "info.GetUSB" },
    EndpointSpec { path: "/system/info/wallpaper.jpg", access: "public", source: "system.info.go:135", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/installer/alpnas/start", access: "authenticated", source: "installer_alpnas.go:73", handler: "alpnasHandleInstallerStart" },
    EndpointSpec { path: "/system/installer/alpnas/state", access: "authenticated", source: "installer_alpnas.go:71", handler: "alpnasHandleInstallerState" },
    EndpointSpec { path: "/system/installer/alpnas/targets", access: "authenticated", source: "installer_alpnas.go:72", handler: "alpnasHandleInstallerTargets" },
    EndpointSpec { path: "/system/iot/execute", access: "authenticated", source: "iot.go:77", handler: "iotManager.HandleExecute" },
    EndpointSpec { path: "/system/iot/icon", access: "authenticated", source: "iot.go:78", handler: "iotManager.HandleIconLoad" },
    EndpointSpec { path: "/system/iot/list", access: "authenticated", source: "iot.go:75", handler: "iotManager.HandleListing" },
    EndpointSpec { path: "/system/iot/listScanner", access: "admin", source: "iot.go:82", handler: "iotManager.HandleScannerList" },
    EndpointSpec { path: "/system/iot/nickname", access: "authenticated", source: "iot.go:79", handler: "iotManager.HandleNickName" },
    EndpointSpec { path: "/system/iot/scan", access: "authenticated", source: "iot.go:74", handler: "iotManager.HandleScanning" },
    EndpointSpec { path: "/system/iot/status", access: "authenticated", source: "iot.go:76", handler: "iotManager.HandleGetDeviceStatus" },
    EndpointSpec { path: "/system/log/list", access: "admin", source: "system.info.go:193", handler: "logViewer.HandleListLog" },
    EndpointSpec { path: "/system/log/read", access: "admin", source: "system.info.go:194", handler: "logViewer.HandleReadLog" },
    EndpointSpec { path: "/system/module/install", access: "authenticated", source: "module.go:148", handler: "HandleModuleInstall" },
    EndpointSpec { path: "/system/modules/getDefault", access: "public", source: "module.go:34", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/modules/getLaunchPara", access: "public", source: "module.go:37", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/modules/installViaZip", access: "public", source: "module.go:47", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/modules/list", access: "public", source: "module.go:31", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/modules/reload", access: "admin", source: "module.go:41", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/network/connectWifi", access: "authenticated", source: "wifi.go:43", handler: "network_wifi_handleConnect" },
    EndpointSpec { path: "/system/network/getNICUsage", access: "authenticated", source: "network.go:76", handler: "netstat.HandleGetNetworkInterfaceStats" },
    EndpointSpec { path: "/system/network/getNICinfo", access: "authenticated", source: "network.go:63", handler: "network.GetNICInfo" },
    EndpointSpec { path: "/system/network/getPing", access: "authenticated", source: "network.go:64", handler: "network.GetPing" },
    EndpointSpec { path: "/system/network/portforward", access: "authenticated", source: "network.forward.go:61", handler: "portforward_handleForward" },
    EndpointSpec { path: "/system/network/power", access: "authenticated", source: "wifi.go:49", handler: "network_wifi_handleWiFiPower" },
    EndpointSpec { path: "/system/network/removeWifi", access: "authenticated", source: "wifi.go:44", handler: "network_wifi_handleWiFiRemove" },
    EndpointSpec { path: "/system/network/scanWifi", access: "authenticated", source: "wifi.go:42", handler: "network_wifi_handleScan" },
    EndpointSpec { path: "/system/network/server/endpoints", access: "authenticated", source: "network.go:498", handler: "NetworkHandleGetFileServerEndpoints" },
    EndpointSpec { path: "/system/network/server/list", access: "authenticated", source: "network.go:497", handler: "NetworkHandleGetFileServerServiceList" },
    EndpointSpec { path: "/system/network/server/status", access: "authenticated", source: "network.go:499", handler: "NetworkHandleGetFileServerStatus" },
    EndpointSpec { path: "/system/network/server/toggle", access: "admin", source: "network.go:500", handler: "NetworkHandleFileServerToggle" },
    EndpointSpec { path: "/system/network/webdav/clear", access: "authenticated", source: "network.go:353", handler: "WebDAVManager.HandleClearAllPending" },
    EndpointSpec { path: "/system/network/webdav/edit", access: "authenticated", source: "network.go:352", handler: "WebDAVManager.HandlePermissionEdit" },
    EndpointSpec { path: "/system/network/webdav/list", access: "public", source: "network.go:351", handler: "WebDAVManager.HandleConnectionList" },
    EndpointSpec { path: "/system/network/webdav/status", access: "authenticated", source: "network.go:354", handler: "WebDAVManager.HandleStatusChange" },
    EndpointSpec { path: "/system/network/wifiinfo", access: "authenticated", source: "wifi.go:45", handler: "network_wifi_handleWiFiInfo" },
    EndpointSpec { path: "/system/network/www/toggle", access: "authenticated", source: "network.go:93", handler: "userWwwHandler.HandleToggleHomepage" },
    EndpointSpec { path: "/system/network/www/webRoot", access: "authenticated", source: "network.go:94", handler: "userWwwHandler.HandleSetWebRoot" },
    EndpointSpec { path: "/system/permission/delgroup", access: "admin", source: "permission.go:60", handler: "permissionHandler.HandleGroupRemove" },
    EndpointSpec { path: "/system/permission/editgroup", access: "admin", source: "permission.go:59", handler: "permissionHandler.HandleGroupEdit" },
    EndpointSpec { path: "/system/permission/listgroup", access: "public", source: "permission.go:35", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/permission/newgroup", access: "admin", source: "permission.go:58", handler: "permissionHandler.HandleGroupCreate" },
    EndpointSpec { path: "/system/power/accessCheck", access: "public", source: "hardware.power.go:29", handler: "hardware_power_checkIfHardware" },
    EndpointSpec { path: "/system/power/restart", access: "public", source: "hardware.power.go:16", handler: "hardware_power_restart" },
    EndpointSpec { path: "/system/power/shutdown", access: "public", source: "hardware.power.go:15", handler: "hardware_power_poweroff" },
    EndpointSpec { path: "/system/register/cleanUserRegisterInfo", access: "admin", source: "register.go:89", handler: "register_handleRegisterCleaning" },
    EndpointSpec { path: "/system/register/email", access: "authenticated", source: "register.go:53", handler: "registerHandler.HandleEmailChange" },
    EndpointSpec { path: "/system/register/getAllowRegistry", access: "admin", source: "register.go:80", handler: "register_handleGetAllowRegistry" },
    EndpointSpec { path: "/system/register/listUserEmails", access: "admin", source: "register.go:86", handler: "register_handleEmailListing" },
    EndpointSpec { path: "/system/register/setAllowRegistry", access: "admin", source: "register.go:83", handler: "register_handleToggleRegistry" },
    EndpointSpec { path: "/system/register/setDefaultGroup", access: "admin", source: "register.go:77", handler: "register_handleSetDefaultGroup" },
    EndpointSpec { path: "/system/reset/confirmPasswordReset", access: "public", source: "system.resetpw.go:26", handler: "system_resetpw_confirmReset" },
    EndpointSpec { path: "/system/reset/validateResetKey", access: "public", source: "system.resetpw.go:25", handler: "system_resetpw_validateResetKeyHandler" },
    EndpointSpec { path: "/system/setting/list", access: "public", source: "setting.go:34", handler: "system_setting_handleListing" },
    EndpointSpec { path: "/system/storage/ftp/passivemode", access: "admin", source: "network.go:368", handler: "FTPManager.HandleFTPPassiveModeSettings" },
    EndpointSpec { path: "/system/storage/ftp/setPort", access: "admin", source: "network.go:367", handler: "FTPManager.HandleFTPSetPort" },
    EndpointSpec { path: "/system/storage/ftp/start", access: "admin", source: "network.go:362", handler: "FTPManager.HandleFTPServerStart" },
    EndpointSpec { path: "/system/storage/ftp/status", access: "admin", source: "network.go:365", handler: "FTPManager.HandleFTPServerStatus" },
    EndpointSpec { path: "/system/storage/ftp/stop", access: "admin", source: "network.go:363", handler: "FTPManager.HandleFTPServerStop" },
    EndpointSpec { path: "/system/storage/ftp/updateGroups", access: "admin", source: "network.go:366", handler: "FTPManager.HandleFTPAccessUpdate" },
    EndpointSpec { path: "/system/storage/ftp/upnp", access: "admin", source: "network.go:364", handler: "FTPManager.HandleFTPUPnP" },
    EndpointSpec { path: "/system/storage/pool/bridge", access: "admin", source: "storage.pool.go:55", handler: "HandleFSHBridging" },
    EndpointSpec { path: "/system/storage/pool/checkBridge", access: "admin", source: "storage.pool.go:56", handler: "HandleFSHBridgeCheck" },
    EndpointSpec { path: "/system/storage/pool/edit", access: "admin", source: "storage.pool.go:54", handler: "HandleFSHEdit" },
    EndpointSpec { path: "/system/storage/pool/list", access: "admin", source: "storage.pool.go:48", handler: "HandleListStoragePools" },
    EndpointSpec { path: "/system/storage/pool/listraw", access: "admin", source: "storage.pool.go:49", handler: "HandleListStoragePoolsConfig" },
    EndpointSpec { path: "/system/storage/pool/newHandler", access: "admin", source: "storage.pool.go:50", handler: "HandleStorageNewFsHandler" },
    EndpointSpec { path: "/system/storage/pool/reload", access: "admin", source: "storage.pool.go:52", handler: "HandleStoragePoolReload" },
    EndpointSpec { path: "/system/storage/pool/removeHandler", access: "admin", source: "storage.pool.go:51", handler: "HandleStoragePoolRemove" },
    EndpointSpec { path: "/system/storage/pool/toggle", access: "admin", source: "storage.pool.go:53", handler: "HandleFSHToggle" },
    EndpointSpec { path: "/system/storage/samba/activate", access: "authenticated", source: "network.go:378", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/storage/samba/add", access: "admin", source: "network.go:395", handler: "SambaShareManager.AddSambaShare" },
    EndpointSpec { path: "/system/storage/samba/addUser", access: "admin", source: "network.go:398", handler: "SambaShareManager.NewSambaUser" },
    EndpointSpec { path: "/system/storage/samba/deactivate", access: "admin", source: "network.go:390", handler: "SambaShareManager.DeactiveUserAccount" },
    EndpointSpec { path: "/system/storage/samba/delUser", access: "admin", source: "network.go:399", handler: "SambaShareManager.DelSambaUser" },
    EndpointSpec { path: "/system/storage/samba/editPath", access: "admin", source: "network.go:396", handler: "SambaShareManager.HandleSharePathChange" },
    EndpointSpec { path: "/system/storage/samba/list", access: "admin", source: "network.go:394", handler: "SambaShareManager.ListSambaShares" },
    EndpointSpec { path: "/system/storage/samba/listUsers", access: "admin", source: "network.go:400", handler: "SambaShareManager.ListSambaUsers" },
    EndpointSpec { path: "/system/storage/samba/myshare", access: "admin", source: "network.go:391", handler: "SambaShareManager.HandleUserSmbStatusList" },
    EndpointSpec { path: "/system/storage/samba/myshare/delete", access: "admin", source: "network.go:392", handler: "SambaShareManager.DelUserSambaShare" },
    EndpointSpec { path: "/system/storage/samba/remove", access: "admin", source: "network.go:397", handler: "SambaShareManager.DelSambaShare" },
    EndpointSpec { path: "/system/storage/samba/status", access: "admin", source: "network.go:393", handler: "SambaShareManager.SmbdStates" },
    EndpointSpec { path: "/system/storage/samba/updateShareUsers", access: "admin", source: "network.go:401", handler: "SambaShareManager.HandleAccessUserUpdate" },
    EndpointSpec { path: "/system/storage/sftp/port", access: "admin", source: "network.go:357", handler: "SFTPManager.HandleListeningPort" },
    EndpointSpec { path: "/system/storage/sftp/upnp", access: "admin", source: "network.go:358", handler: "SFTPManager.HandleToogleUPnP" },
    EndpointSpec { path: "/system/storage/sftp/users", access: "admin", source: "network.go:359", handler: "SFTPManager.HandleGetConnectedClients" },
    EndpointSpec { path: "/system/storage/tftp/defaultUser", access: "admin", source: "network.go:373", handler: "TFTPManager.HandleTFTPDefaultUser" },
    EndpointSpec { path: "/system/storage/tftp/setPort", access: "admin", source: "network.go:372", handler: "TFTPManager.HandleTFTPPort" },
    EndpointSpec { path: "/system/storage/tftp/status", access: "admin", source: "network.go:371", handler: "TFTPManager.HandleTFTPServerStatus" },
    EndpointSpec { path: "/system/subservice/kill", access: "admin", source: "subservice.go:61", handler: "ssRouter.HandleKillSubService" },
    EndpointSpec { path: "/system/subservice/list", access: "admin", source: "subservice.go:60", handler: "ssRouter.HandleListing" },
    EndpointSpec { path: "/system/subservice/start", access: "admin", source: "subservice.go:62", handler: "ssRouter.HandleStartSubService" },
    EndpointSpec { path: "/system/update/checkpending", access: "admin", source: "system.info.go:158", handler: "updates.HandlePendingCheck" },
    EndpointSpec { path: "/system/update/checksize", access: "admin", source: "system.info.go:157", handler: "updates.HandleUpdateCheckSize" },
    EndpointSpec { path: "/system/update/download", access: "admin", source: "system.info.go:156", handler: "updates.HandleUpdateDownloadRequest" },
    EndpointSpec { path: "/system/update/platform", access: "admin", source: "system.info.go:159", handler: "updates.HandleGetUpdatePlatformInfo" },
    EndpointSpec { path: "/system/update/restart", access: "admin", source: "system.info.go:162", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/users/editUser", access: "admin", source: "user.go:99", handler: "user_handleUserEdit" },
    EndpointSpec { path: "/system/users/interfaceinfo", access: "public", source: "user.go:59", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/users/list", access: "public", source: "user.go:51", handler: "user_handleList" },
    EndpointSpec { path: "/system/users/profilepic", access: "public", source: "user.go:64", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/users/removeUser", access: "admin", source: "user.go:100", handler: "user_handleUserRemove" },
    EndpointSpec { path: "/system/users/userinfo", access: "public", source: "user.go:54", handler: "func(w http.ResponseWriter, r *http.Request" },
    EndpointSpec { path: "/system/ws", access: "authenticated", source: "network.go:116", handler: "WebSocketRouter.HandleWebSocketRouting" },
];

pub fn lookup(path: &str) -> Option<&'static EndpointSpec> { ENDPOINTS.iter().find(|e| e.path == path) }
